### ISSUE TITLE
Тайный Антоша. От кого прячется? 

### ISSUE THREAD

**Issue by vitalii17** [sledgeh/Summary-of-PCB-manufactors-in-Ukraine-and-abroad-June-2015#1]
Заказывал один раз платы. Сделали хорошо и быстро, но с самим Антощенком пообщаться так и не удалось. Да и, говорят, он очень сложный в общении.
Хотелось бы знать, от кого он прячется и почему за столько лет нельзя уладить этот вопрос?
На всех форумах и статьях, где упоминаются его контакты, они удалены по его же просьбе. 
Зачем он себе делает такую антирекламу? Мне с трудом удалось выудить контакты что бы сделать заказ.

**Comment by qywx** [comment]
Пришло уведомление от GitHub что контактные данные просят и требуют скрыть. Н дней на устранение. Полное, во всех коммитах путём `git filter-branch` или как-то так.
Так я поднял свой навык владения Git `    :^)  ` `👍 `

**Comment by vitalii17** [comment]
Я не понял про Git. Мне вот другое интересно: почему и от кого он прячется? И почему за столько лет нельзя было уладить этот вопрос?

**Comment by qywx** [comment]
не могу знать. а гадать смысла мало.

Про Гит. Это значит удалить контактные данные из всей истории коммитов. Так делают, если, например, случайно пароль от сервера положили в репозиторий.
